name: CI Build

on:
  push:
    branches: [master]
    paths-ignore:
      - "**/*.md"
      - "**/*.gitignore"
      - "**/*.gitattributes"
  pull_request:
    branches: [master]
  workflow_dispatch:
permissions:
  contents: read

env:
  DOTNET_NOLOGO: true # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true # Disable sending .NET CLI telemetry

jobs:
  # MAUI Windows Build
  build-windows:
    runs-on: windows-2022
    name: Windows Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore src/BiodiversityCoder/BiodiversityCoder.csproj

      - name: Build MAUI Windows
        run: dotnet publish src/BiodiversityCoder/BiodiversityCoder.csproj -c Debug -f net6.0-windows10.0.19041.0 --no-restore

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: BiodiversityCoder-windows-ci-build
          path: src/BiodiversityCoder/bin/Debug/net6.0-windows10.0.19041.0/win10-x64/AppPackages/BiodiversityCoder*/BiodiversityCoder*.msix

  # MAUI MacCatalyst Build
  build-mac:
    runs-on: macos-12
    name: MacCatalyst Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore src/BiodiversityCoder/BiodiversityCoder.csproj

      - name: Build MAUI MacCatalyst
        run: dotnet publish src/BiodiversityCoder/BiodiversityCoder.csproj -c Debug -f net6.0-maccatalyst --no-restore -p:BuildIpa=True

      - name: Upload MacCatalyst Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: BiodiversityCoder-macos-ci-build
          path: src/BiodiversityCoder/bin/Debug/net6.0-maccatalyst/maccatalyst-x64/publish/*.pkg
